### ISSUE TITLE
oppo自带浏览器屏蔽996.icu的github

### ISSUE THREAD

**Issue by Longhao-Chen** [996browser/996.BROWSER#10]

**Comment by 996browser** [comment]
请提供截图。

**Comment by Longhao-Chen** [comment]
![Screenshot_2019-04-16-13-00-30-51](https://user-images.githubusercontent.com/35413451/56183272-6cc0d780-6048-11e9-911a-a9204fb9ee76.png)

996.icu可以正常访问，但访问https://github.com/996icu/996.ICU就出现了这个界面。

**Comment by 996browser** [comment]
已提交。
* [4fa83aa](https://github.com/996browser/996.BROWSER/commit/4fa83aa10b5c2917be811a4d69b4c61ec8b33bdd)
* [73d7195](https://github.com/996browser/996.BROWSER/commit/73d71955f6d5f9b8cd8590cc815bae059ebd0241)
