### ISSUE TITLE
华为自带浏览器屏蔽996.icu

### ISSUE THREAD

**Issue by sigui993** [996browser/996.BROWSER#12]

**Comment by sigui993** [comment]
不知道如何发送图片,麻烦谁指导一下可以不

**Comment by IMVector** [comment]
> 
> 
> 不知道如何发送图片,麻烦谁指导一下可以不

fork到本地，把图片加到项目里，然后pull request

**Comment by sigui993** [comment]
![aa](https://github.com/sigui993/996.BROWSER/blob/master/Screenshot_20190417-151258.jpg)

> > 不知道如何发送图片,麻烦谁指导一下可以不
> 
> fork到本地，把图片加到项目里，然后pull request

不好意思,,搞了一会,还是没弄好,能再指导指导么?我qq1215605237
我点了fork,然后加入了新文件,之后电流pull request ,但没有把图片加上去

**Comment by IMVector** [comment]
> 
> 
> ![Image of Yaktocat](https://camo.githubusercontent.com/5215e6fe0e2fc740eb8d91fe380287294fcacca5/68747470733a2f2f6f63746f6465782e6769746875622e636f6d2f696d616765732f79616b746f6361742e706e67)
> 
> > > 不知道如何发送图片,麻烦谁指导一下可以不
> > 
> > 
> > fork到本地，把图片加到项目里，然后pull request
> 
> 不好意思,,搞了一会,还是没弄好,能再指导指导么?我qq1215605237
> 我点了fork,然后加入了新文件,之后电流pull request ,但没有把图片加上去
你pull request后，要等作者合并才行

**Comment by sigui993** [comment]
> > > > 不知道如何发送图片,麻烦谁指导一下可以不
> > > 
> > > 
> > > fork到本地，把图片加到项目里，然后pull request
> > 
> > 
> > 不好意思,,搞了一会,还是没弄好,能再指导指导么?我qq1215605237
> > 我点了fork,然后加入了新文件,之后电流pull request ,但没有把图片加上去
> > 你pull request后，要等作者合并才行

好的,我想试试如何在这里发送图片呢,刚才我发送了一张demo的图片,但是换成我的链接后就不是图片了

**Comment by 996browser** [comment]
看到你的PR #13 了，建议修改截图名称为`huawei_mobile_1.jpg`，并移动至`screenshots`文件夹。

同时建议在[README.md](https://github.com/996browser/996.BROWSER/blob/master/README.md)追加条目。

**Comment by Dobby233Liu** [comment]
qq浏览器和华为浏览器貌似内核相同

**Comment by 996browser** [comment]
你的PR #13 因图片提交不符合规范，且不再活动，我将你提交的图片下载并重新提交，并在`README.md`追加了`华为浏览器`的条目。
