### ISSUE TITLE
[白名单][Android]未屏蔽 996.icu 的浏览器：“X浏览器”

### ISSUE THREAD

**Issue by yiding-he** [996browser/996.BROWSER#17]
该浏览器是个人开发者作品，在酷安上可以搜到：
https://www.coolapk.com/apk/com.mmbox.xbrowser

![Screenshot_20190502-170855](https://user-images.githubusercontent.com/900606/57065917-70698500-6cfd-11e9-996a-7f7e2a430f54.jpg)
![Screenshot_20190502-170948](https://user-images.githubusercontent.com/900606/57065918-71021b80-6cfd-11e9-93fe-d19aabb5c6bf.jpg)

**Comment by rtsui-harmonicinc** [comment]
就一個webview
