### ISSUE TITLE
我手机上的小米浏览器并没有屏蔽 996.icu

### ISSUE THREAD

**Issue by shgopher** [996browser/996.BROWSER#22]

**Comment by shgopher** [comment]
我听说 微信上也不能访问 ，问题是我的也行啊。。。我真的很好奇屏蔽是什么感觉，等我下载qq浏览器试试，试了试我的qq浏览器 也没屏蔽啊。这说不过去啊。。。。

**Comment by shgopher** [comment]
https://www.youtube.com/watch?v=IsmDDYJ5FCo&feature=youtu.be 我刚录播了一段我真的奇了怪了，我的没被屏蔽。

**Comment by hueidou** [comment]
> 由于各厂商浏览器已经放开屏蔽，只能参考相关文章内的截图。（如有版权问题，可告知并下撤） 提交PR增加条目时，请提供截图证明。

README里提到了。

**Comment by plh97** [comment]
反正我就只用chrome. 其他browser不管也不看
