### ISSUE TITLE
因为腾讯大王卡一直使用手机版QQ浏览器，最近发现已经完全屏蔽996.icu了

### ISSUE THREAD

**Issue by liyujiang-gzu** [996browser/996.BROWSER#7]
因为腾讯大王卡一直使用手机版QQ浏览器，之前只是弹窗提示风险，现在已经完全屏蔽996.icu，不允许访问了

**Comment by liyujiang-gzu** [comment]
现在只有**在url后面加?号再加随机参数**才能访问

**Comment by 996browser** [comment]
列表已经包含`QQ浏览器`，不过可以提供截图上传至`screenshots`文件夹。
