### ISSUE TITLE
哈哈哈哈    手机电脑全换了chrome全家桶   

### ISSUE THREAD

**Issue by qq3d1415926** [996browser/996.BROWSER#8]
哈哈哈哈    手机电脑全换了chrome全家桶

**Comment by wodesj33** [comment]
哎。。逼着我们抛弃他们

**Comment by 1104049235** [comment]
然鹅只是一小部分用户而已

**Comment by musicomputer-tao** [comment]
用Firefox的表示不服。以前在Windows10上用四家浏览器（Microsoft Edge，Opera，Google Chrome，Mozilla/北京谋智 Firefox），在手机上用九家浏览器（乐pro3 LEX720|Google Chrome，北京谋智 Firefox，Mozilla Firefox focus，360 极速浏览器，Opera，阿里巴巴 夸克，凤凰浏览器，ADM Browser，others of two）；现在在macOS（HighSierraAMD 黑苹果）上用三家浏览器（Apple Safari，北京谋智 Firefox，Tor Browser），手机上用三家浏览器（老妈乐 U5483|Mozilla Firefox Focus，Google Chrome beta-69，FV查看器）。说明一下，乐pro3已坏，不得不用从抽屉里翻出来的老妈乐U5483.U5483是sc8830（Platform）/sc9832a（硬件）平台的，包含四核（768MHz-1300MHz）cortex-A7，mali-400MP，1G RAM+8G 存储，跑安卓六（360 1.0 OS？）系统。性能表现嘛，比如打开微信6.7.3，（包含太极阴模块）从打开到消息过来大概需要五分钟的时间，在这手机上用小草客户端浏览几个图贴后网页会自动重新加载（肯定是内存不足所致），相机上几乎没有任何优化（跟乐pro3上的谷歌相机的表现差得太多太多了，说实话我感觉小米体验店里的小米9自带的相机拍照水准都不如乐pro3 IMX298+谷歌相机 6.0 BSG版本，米九的涂抹感太严重噪点又比较多曝光也有所不足，照片整体上偏糊。谷歌相机出的图像是真清楚，照片的非焦点处基本上也没有多模糊的。尤其是配着BSG的军刀算法用，那是真棒，当时我测算法在手机上表现时，躺床上隔着玻璃照楼下大概二三百米远的路口，看到选军刀算法后照出的图片中，居然把我家玻璃上的污渍与灰尘也照了进去，而且路口上的车的体现质量也很好，不禁觉得这实在令人感叹！），这些情况我都差不多适应了……况且现在macOS的显卡驱动问题还没被解决，自己玩不了任何游戏还不能看视频，夸张地说真是有点窝火。（macOS10.13.3，显卡i-Cafe 7850 1G，显示器HKC S9809；我已用lilu+whatevergreen+RadeonDeInit，借助AMD Framebuffer Utility与Radeon BIOS decoder配过多次Framebuffer，显卡可能是七彩虹网吧版 有DVI，HDMI与DP接口，显示器最大分辨率1366*768接口VGA，用着的还有DVI-VGA转接头；自己在amd-osx与insanelymac发帖问着但没有获得任何回应，没有远景账号更没钱。真是的啊。）

**Comment by WangNianyi2001** [comment]
請善用 issue 區，issue 不是拿來灌水的
