### ISSUE TITLE
提供js脚本, 屏蔽这些浏览器

### ISSUE THREAD

**Issue by jeffli678** [996browser/996.BROWSER#9]
在自己的网站上屏蔽这些浏览器

**Comment by liyujiang-gzu** [comment]
想法需要改进一下：当用户使用非chrome、firefox、opera、safari、ie、edge时，提示用户他使用的浏览器有泄漏隐私的风险，强烈建议换用chrome或firefox

**Comment by WangNianyi2001** [comment]
改 UA 的話怎麼辦呢
而且除了程序員開發的個人網頁以外，幾乎沒有人想要損失一大票潛在用戶吧……
*理想很美好，現實太骨感*

**Comment by songsammy** [comment]
360UA了解一下

**Comment by jeffli678** [comment]
已经过了很久了，不过还是想说两句。这个的初衷是在自己的个人网站上进行屏蔽，所以改UA这样的手段并不在我考虑之列。如果有的人非要用这样的浏览器，我也不能把他们怎么样。

**Comment by songsammy** [comment]
361安全浏览器了解一下.

**Comment by songsammy** [comment]
这个它本身UA就是用chrome

**Comment by jeffli678** [comment]
360浏览器这种，有js脚本可以具体识别浏览器类型的，不仅参考ua，还有许多别的特性
